name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push 1
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: helpys/jena-fuseki:latest
        
    - name: DigitalOcean App Platform deployment
    uses: digitalocean/app_action@v1.1.2  # replace this with current version from https://github.com/digitalocean/app_action/releases
      with:
        app_name: my_DO_app
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
